
const hookSeed = (
{
        size: "US 7 / 4.5mm",
        brand: "Chiagoo",
        material: "metal",
        inUse: false,
        project: "",
        notes: "best for yokes",
        favorite: true,
        replace: false,
        style: "circular",
        long: "60 inch",
        point: "",
        completeSet: true,
        image: ""
},
{
    size: "US 7 / 4.5mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: true,
    replace: false,
    style: "circular",
    long: "30 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 7 / 4.5mm",
    brand: "Chiagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "great for sleeves",
    favorite: true,
    replace: false,
    style: "Circular",
    long: "12 inch",
    point: "short",
    completeSet: true,
    image: ""
},
{
    size: "",
    brand: "",
    material: "",
    inUse: true,
    project: "",
    notes: "",
    favorite: true,
    replace: false,
    style: "",
    long: "",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 7 / 4.5mm",
    brand: "Chicagoo",
    material: "wood",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "",
    long: "16 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 6 / 4.0mm",
    brand: "Brittany",
    material: "bamboo",
    inUse: false,
    project: "",
    notes: "",
    favorite: true,
    replace: false,
    style: "DPN",
    long: "",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 6 / 4.0mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: true,
    replace: false,
    style: "Circular, red lace",
    long: "30",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 6 / 4.0mm",
    brand: "Chiagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "Circular",
    long: "40 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 6 / 4.0mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "Circular",
    long: "60 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 5 / 3.75mm",
    brand: "Brittany",
    material: "bamboo",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "DPN",
    long: "",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 5 / 3.75mm",
    brand: "Unknown",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "DPN",
    long: "",
    point: "",
    completeSet: false,
    image: ""
},
{
    size: "US 5 / 3.75mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "great for yokes",
    favorite: true,
    replace: false,
    style: "Circular",
    long: "60 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 6 / 4.0mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: true,
    project: "Outline Raglan",
    notes: "",
    favorite: true,
    replace: false,
    style: "circular red lace",
    long: "30 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 2 / 2.75mm",
    brand: "Brittany",
    material: "bamboo",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "DPN",
    long: "",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 2 / 2.75mm",
    brand: "Chiagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "perfect for socks",
    favorite: false,
    replace: false,
    style: "red lace",
    long: "8 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 2 / 2.75mm",
    brand: "Chiagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "red lace",
    long: "12 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 3 / 3.25mm",
    brand: "Unknown",
    material: "metal",
    inUse: true,
    project: "Outline Tank, reenforcing neckline",
    notes: "",
    favorite: true,
    replace: false,
    style: "DPN",
    long: "",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 3 / 3.25mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "great for socks",
    favorite: false,
    replace: false,
    style: "red lace",
    long: "8 inch",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 2.5 / 3.0mm",
    brand: "Chicagoo",
    material: "wood",
    inUse: false,
    project: "",
    notes: "best for hats",
    favorite: false,
    replace: false,
    style: "circular",
    long: "16 inch ",
    point: "",
    completeSet: true,
    image: ""
},
{
    size: "US 4 / 3.5mm",
    brand: "Chicagoo",
    material: "metal",
    inUse: false,
    project: "",
    notes: "",
    favorite: false,
    replace: false,
    style: "Circular",
    long: "24 inch",
    point: "",
    completeSet: true,
    image: ""
}
)