
const yarnSeed = (
{
    brand: "Modus Operandi Fibers",
    name: "Cotton Sport",
    color: "Terracotta",
    yards: 285,
    fiber: "cotton",
    weight: "sport",
    purchaseDate: "08/18/2022",
    skeins: 6,
    store: "Modus Operandi Fibers",
    note: "Discount for Outline Ranglan from indie dyer",
    image: ""
},
{
    brand: "Ritual Dyes",
    name: "Undine",
    color: "Jewelweed",
    yards: 382,
    fiber: "60/40 cotton/linen",
    weight: "fingering",
    purchaseDate: "08/01/2022",
    skeins: 4,
    store: "Ritual Dyes",
    note: "Bought to make Outline Tank or So Summer Shirt",
    image: ""
},
{
    brand: "Hedgehog Fibers",
    name: "Sock",
    color: "Harajuku",
    yards: 437,
    fiber: "90/10 merino wool/nylon",
    weight: "sock",
    purchaseDate: "03/01/2022",
    skeins: 3,
    store: "Wool and Company",
    note: "Bought for a Cozy Classic Raglan Light",
    image: ""
},{
    brand: "Kelbourne Woolens",
    name: "Perennial",
    color: "Pink",
    yards: 497,
    fiber: "60/25/15 sw merino/suri alpaca/nylon",
    weight: "super fine",
    purchaseDate: "05/01/2022",
    skeins: 2,
    store: "Kelbourne Woolens",
    note: "Bought for Ripple Halter Tank",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Navy",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "05/01/2022",
    skeins: 3,
    store: "Stonehedge Fiber Mill",
    note: "CC2 for my Tecumseh",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Roasted Pumpkin",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "CC1 for my Tecumseh",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Beaches",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Tecumseh",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "White",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "For my Polyrhythm",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Black",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Storm",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Autumn Gold",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Sage",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Seabreeze",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Hunter Green",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Peaches and Cream",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Future Cozy Classic Raglan",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Petosky Stone",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Pewter",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Wheat",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Raspberry",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 4,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Great Lakes",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 5,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Ivy",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 2,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Stonehedge Fiber Mill",
    name: "Shepherd's Wool",
    color: "Crazy Natural",
    yards: 250,
    fiber: "wool",
    weight: "worsted",
    purchaseDate: "01/01/2022",
    skeins: 6,
    store: "Stonehedge Fiber Mill",
    note: "Socking up!",
    image: ""
},{
    brand: "Ritual Dyes",
    name: "Undine",
    color: "Natural",
    yards: 382,
    fiber: "60/40 cotton/linen",
    weight: "fingering",
    purchaseDate: "06/01/2022",
    skeins: 4,
    store: "Ritual Dyes",
    note: "For Outline Tank",
    image: ""
},{
    brand: "Ritual Dyes",
    name: "Undine",
    color: "Slate",
    yards: 382,
    fiber: "60/40 cotton/linen",
    weight: "fingering",
    purchaseDate: "06/01/2022",
    skeins: 4,
    store: "Ritual Dyes",
    note: "For Outline Tank",
    image: ""
},{
    brand: "Irish Artisan Yarn",
    name: "IAY",
    color: "Dingle",
    yards: 375,
    fiber: "60% SW merino / 20% yak 20% silk",
    weight: "super fine",
    purchaseDate: "05/17/2022",
    skeins: 1,
    store: "Beautiful Knitters in London",
    note: "Bought on London Trip",
    image: ""
},{
    brand: "Irish Artisan Yarn",
    name: "IAY",
    color: "Rust",
    yards: 375,
    fiber: "65% SW merino / 20% bamboo / 15% silk",
    weight: "super fine",
    purchaseDate: "05/17/2022",
    skeins: 1,
    store: "Beautiful Knitters in London",
    note: "Bought on London Trip",
    image: ""
},{
    brand: "West Yorkshire Spinners",
    name: "Exquisite",
    color: "Noir",
    yards: 437,
    fiber: "80% Falkland Wool 20% Mulberry Silk",
    weight: "Fingering",
    purchaseDate: "05/15/2022",
    skeins: 1,
    store: "Beautiful Knitters",
    note: "Bought on London trip",
    image: ""
},{
    brand: "West Yorkshire Spinners",
    name: "Exquisite",
    color: "Knightsbridge",
    yards: 437,
    fiber: "80% Falkland Wool 20% Mulberry Silk",
    weight: "Fingering",
    purchaseDate: "05/15/2022",
    skeins: 1,
    store: "Beautiful Knitters",
    note: "Bought on London trip",
    image: ""
},{
    brand: "Life In The Long Grass",
    name: "Moon",
    color: "Jade Grey",
    yards: 400,
    fiber: "20% silk 80% sw merino",
    weight: "fingering",
    purchaseDate: "none",
    skeins: 1,
    store: "",
    note: "A gift from Holly's trip to Ireland",
    image: ""
}
)